

import { CartProvider } from "@/Context/cartContext";
import "./globals.css";
import "/public/css/bootstrap.min.css"
import "/public/booticon/font/bootstrap-icons.css"
import "/public/aos-master/dist/aos.css"
import Footer from "@/component/Footer";
import Navbar from "@/component/Navbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body >
      <CartProvider>
      
        {children}
        <Footer/>
        </CartProvider>
     
        </body>
    </html>
  );
}
